Fix zero loss tensor in SquadOutputLayer (#1181)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/1181

In SquadOutputLayer we set start and end position losses to zeros. Those tensor objects have `requires_grad` set to True which leads to unused param error.
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss.
```

Reviewed By: borguz

Differential Revision: D18801364

fbshipit-source-id: 400a56b453a85939f8428b378e42e5238cc241e9