Add the ability to pass parameter values to gen-default-config (#856)
Summary:
> pytext gen-default-config DocumentClassificationTask field_names=text,label column_mapping=a:1,b:2

When there's possible conflicts finding the exact parameter, you get a nice error message with the possible paths

  > pytext gen-default-config DocumentClassificationTask freeze=0
  ...
  Exception: Multiple possibilities for freeze=1: task.model.embedding.freeze, task.model.representation.freeze, task.model.representation.lstm.freeze, task.model.decoder.freeze, task.model.output_layer.freeze

Choose the parameter you want by passing the unambiguous suffix of one of the paths

  > pytext gen-default-config DocumentClassificationTask decoder.freeze=0

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/856

Reviewed By: borguz

Differential Revision: D16572740

Pulled By: Titousensei

fbshipit-source-id: e42756a9607a0188a56432ca46b945c233135c3c