Fix bug in StackedBidirectionalRNN for input with batch_size = 1
Summary:
There's no need to squeeze after calling torch.Tenor.sum() because the sum function's default behavior is to squeeze the dimension along which the sum is done. Squeezing explicitly removes batch dimension when batch_size = 1 resulting in the exception

```
torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor
```

Differential Revision: D15609010

fbshipit-source-id: 0bb34efa3d6a127a4cee91d80b158730557f6087