fix train_model_distributed pickle (#231)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/231

This is resolve issue: https://github.com/facebookresearch/pytext/issues/228
TypeError: can't pickle _thread.lock objects because SummaryWriter is unpicklable

Differential Revision: D13776866

fbshipit-source-id: a6f0ff08a74aef385cdd728f66fef01033eeb583