fix OSS import issue by adding __init__.py (#1162)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/1162

Although empty __init__.py is not required since python3.3+, Google Colab's python3.6 still requires it. Missing this file causes error during "from pytext import workflow"

ModuleNotFoundError: No module named 'pytext.torchscript'

Reviewed By: chenyangyu1988, JiesiZhao077

Differential Revision: D18648432

fbshipit-source-id: 6b3a317f6829dd3bac91a0fd84b050baa845baf6