Fix BiLSTM forward crash when input embedding is on GPU (#297)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/297

D14035841 added zero hidden state, but it allocates the tensor on CPU, which would break when the input embedding is on GPU. This broke Assistant integration tests, which were not triggered in the original diff.

https://our.intern.facebook.com/intern/fblearner/details/99310304

```
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu
```

Reviewed By: bethebunny

Differential Revision: D14065899

fbshipit-source-id: 70a8dae5c896ba2dc68342e02083e42883e2e48a