use the latest version of torch and tensorboard (#1412)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/1412

my diff D21435152 got unrelated import error in CircleCI, due to incompatibility between latest torchtext and torch==1.5.0.

e.g.
OSError: /usr/local/lib/python3.6/site-packages/torchtext/_torchtext.so: undefined symbol:

full log: https://app.circleci.com/pipelines/github/facebookresearch/pytext/5111/workflows/fd4040cd-2580-4e2e-a155-1f52b36a898e/jobs/19183/tests

Differential Revision: D22824001

fbshipit-source-id: 3715d5cbe910589a78e7ba7177ee2e20b41bcbee