To make pytext transformer backward compatible
Summary:
The problem: when I load pickled models which were trained before D27528291 (https://github.com/facebookresearch/PyText/commit/4d93420da19f6eb7845f7b2919ec4e5a67831661) I get following errors:
```
File "/data/sandcastle/boxes/fbsource/fbcode/buck-out/opt/gen/aab7ed39/aml/integrity_solutions/ai_gaps_finder/captum_faim#link-tree/pytext/models/representations/transformer/transformer.py", line 102, in forward
    if not self.normalize_before:
  File "/data/sandcastle/boxes/fbsource/fbcode/buck-out/opt/gen/aab7ed39/aml/integrity_solutions/ai_gaps_finder/captum_faim#link-tree/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Transformer' object has no attribute 'normalize_before'
```
and
```
File "/data/sandcastle/boxes/fbsource/fbcode/buck-out/opt/gen/aab7ed39/aml/integrity_solutions/ai_gaps_finder/captum_faim#link-tree/pytext/models/representations/transformer/transformer.py", line 101, in forward
    embedded += embedded_positions
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```
To resolve it Aapo suggested using getattr (https://www.internalfb.com/diff/D27748567?dst_version_fbid=3531774213589023&transaction_fbid=485058112737939)
**So the goal of this diff to keep the same logic but make it work for old models.**

Reviewed By: akyrola

Differential Revision: D28450083

fbshipit-source-id: 8c1aa32ec531ebe69999776670b1bc32d73d9e3f