fix train_model_distributed pickle (#231)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/231

This is resolve issue: https://github.com/facebookresearch/pytext/issues/228
TypeError: can't pickle _thread.lock objects because SummaryWriter is unpicklable

Reviewed By: geof90

Differential Revision: D13776866

fbshipit-source-id: 966886b287679995e31eb7032a264b254ede6001