Add the ability to pass parameter values to gen-default-config
  > pytext gen-default-config DocumentClassificationTask field_names=text,label column_mapping=a:1,b:2

When there's possible conflicts finding the exact parameter, you get a nice error message with the possible paths

  > pytext gen-default-config DocumentClassificationTask freeze=0
  ...
  Exception: Multiple possibilities for freeze=1: task.model.embedding.freeze, task.model.representation.freeze, task.model.representation.lstm.freeze, task.model.decoder.freeze, task.model.output_layer.freeze

Choose the parameter you want by passing the unambiguous suffix of one of the paths

  > pytext gen-default-config DocumentClassificationTask decoder.freeze=0