Fix bug in StackedBidirectionalRNN for input with batch_size = 1 (#658)
Summary:
Pull Request resolved: https://github.com/facebookresearch/pytext/pull/658

There's no need to squeeze after calling `torch.Tensor.sum()` because the sum function's default behavior is to squeeze the dimension along which the sum is done. Squeezing explicitly removes batch dimension when `batch_size = 1` resulting in the exception

```
torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor
```

Reviewed By: borguz

Differential Revision: D15609010

fbshipit-source-id: 2442efe4918ad939b44de9b2bbb2f686cd3e7bef